### ISSUE TITLE
Stop when queue is empty

### ISSUE THREAD

**Issue by EricSmekens** [tutukin/tasks-queue#2]
Hi, I appreciate your work and it works alright. I only have one issue.

I currently use this as a buffer for writing to a serialport. But when the queue is empty, it stops and I have to call execute again. But when I call execute after every pushTask than the timing is not correct.

I currently 'fixed this' by never letting the excute stop. 

```
    else {
    //No tasks, just wait and recheck.- Eric Edit
    this._flagOn('WaitMinTime');
    this.timer.mintime = setTimeout(
        onMinTimePassed,
        this.getMinTime()
    );


    //task  = _getTaskObject.call(this,'stop',undefined);
    //jinn  = new Jinn(this,task);
    //this.emit('stop',jinn);
}
```

I changed it this way. Is there a possibilty you could build this in? Or do you recommend to write my own bufferqueue?

**Comment by tutukin** [comment]
Yes, this is a good feature.

**Comment by EricSmekens** [comment]
I noticed you implemented this! I will integrate it again in my project if I have spare time available!
